package model;

public enum CurrencyCode {
    USD, BIT, ETH, AED, AFN, ALL, AMD, ANG, AOA, ARS, AUD, AWG, AZN, BAM, BBD,
    BDT, BGN, BHD, BMD, BND, BOB, BRL, BSD, BTN, BWP, BYN, BZD,
    CAD, CDF, CHF, CLP, CNY, COP, CRC, CUP, CVE, CZK, DKK, DOP,
    DZD, EGP, ETB, EUR, FJD, GBP, GEL, GHS, GTQ, GYD, HKD, HNL,
    HRK, HUF, IDR, ILS, INR, IQD, IRR, ISK, JMD, JOD, JPY, KES,
    KGS, KHR, KMF, KRW, KWD, KZT, LBP, LKR, LRD, LSL, LYD, MAD,
    MDL, MGA, MKD, MMK, MNT, MOP, MRU, MUR, MVR, MWK, MXN, MYR,
    MZN, NAD, NGN, NIO, NOK, NPR, NZD, OMR, PAB, PEN, PGK, PHP,
    PKR, PLN, PYG, SGD
}
